language: node_js
node_js:
  - 10.16.3
addons:
  sonarcloud:
    organization: shubham-thakare
    token: 
      secure: $SONAR_TOKEN
script:
  - npm run test:c -- -u
  - sonar-scanner
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master