language: node_js
node_js:
  - 10.16.3
cache:
  directories:
  - node_modules
addons:
  sonarcloud:
    organization: shubham-thakare
script:
  - npm run test:c -- -u
  - sonar-scanner
deploy:
  script:
    - npm run build
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: build
  on:
    branch: master